# Generated by Django 3.1.3 on 2020-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0006_remove_article_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='cat', to='admin-panel.Category'),
        ),
    ]
