# Generated by Django 3.1.3 on 2020-11-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0008_auto_20201111_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='cat',
        ),
    ]
